version: "3.8"
services:
  web:
    build:
      context: ./
      target: runner
    ports:
      - "0.0.0.0:3050:3000"
    environment:
      NODE_ENV: production
    networks:
      - webnet
networks:
  webnet:
    external: 
      name: webnet
