version: "3.8"
services:
  web:
    container_name: motoshop7
    build:
      context: ./
      target: runner
    ports:
      - "0.0.0.0:3055:3000"
    environment:
      NODE_ENV: production
    networks:
      - hasms-front
networks:
  hasms-front:
    name: hasms-front
    external: true 

